--
-- create tables, constraints, sequences and indexes for course
--

-- TABLE
CREATE TABLE COURSE (
  ID INT[18] NOT NULL,
  -- base attributes
  TITLE CHAR (30) NOT NULL,
  DURATION INT[4],
  STARTING_DATE DATE,
  END_DATE DATE,
  CENTER CHAR(30),
  LINK CHAR(50),
  CONTENT CHAR(100),
  -- technical attributes of the table
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY CHAR(20) NOT NULL,
  MODIFIED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_BY CHAR(20) NOT NULL,
  VERSION INT[10] NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE ON COURSE TO WORKER;

-- constraints
ALTER TABLE COURSE ADD CONSTRAINT PK_COURSE PRIMARY KEY (ID);

-- sequences
CREATE SEQUENCE COURSE_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NO CYCLE;

GRANT SELECT, USAGE ON COURSE_SEQ TO WORKER;
