--
-- create tables, constraints, sequences and indexes for course
--

-- TABLE
CREATE TABLE LABEL (
  ID INT[18] NOT NULL,
  -- base attributes
  LABEL_TEXT CHAR (30) NOT NULL,
  LABEL_PARENT INT[18],
  -- technical attributes of the table
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  CREATED_BY CHAR(20) NOT NULL,
  MODIFIED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  MODIFIED_BY CHAR(20) NOT NULL,
  VERSION INT[10] NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE ON LABEL TO WORKER;

-- constraints
ALTER TABLE LABEL ADD CONSTRAINT PK_LABEL PRIMARY KEY (ID);

-- sequences
CREATE SEQUENCE LABEL_SEQ MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NO CYCLE;

GRANT SELECT, USAGE ON LABEL_SEQ TO WORKER;