--
-- create tables, constraints, sequences and indexes for course
--

-- TABLE
CREATE TABLE COURSE (
  ID INT NOT NULL AUTO_INCREMENT,
  -- base attributes
  TITLE VARCHAR(30) NOT NULL,
  TEACHER VARCHAR(30),
  DURATION INT,
  STARTING_DATE DATE,
  END_DATE DATE,
  CENTER VARCHAR(30),
  LINK VARCHAR(50),
  CONTENT VARCHAR(100),
  -- technical attributes of the table
  CREATED_AT TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR(20) NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(20) NOT NULL,
  VERSION INT NOT NULL,
  PRIMARY KEY (ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON COURSE TO CONNECT;
