--
-- create tables, constraints, sequences and indexes for course
--

-- TABLE
CREATE TABLE LOGIN (
  ID INT NOT NULL AUTO_INCREMENT,
  -- base attributes
  TITLE VARCHAR(30) NOT NULL,
  USERNAME VARCHAR(20),
  PASSWORD VARCHAR(10),
  URL VARCHAR(100),
  -- technical attributes of the table
  CREATED_AT TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR(20) NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(20) NOT NULL,
  VERSION INT NOT NULL,
  PRIMARY KEY (ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON LOGIN TO CONNECT;


