--
-- create tables, constraints, sequences and indexes for course
--

-- TABLE
CREATE TABLE LABEL (
  ID INT NOT NULL AUTO_INCREMENT,
  -- base attributes
  LABEL_TEXT VARCHAR (30) NOT NULL,
  LABEL_ORDER INT,
  LABEL_PARENT INT,
  -- technical attributes of the table
  CREATED_AT TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR(20) NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(20) NOT NULL,
  VERSION INT NOT NULL,
  PRIMARY KEY (ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON LABEL TO CONNECT;

