--
-- create tables, constraints, sequences and indexes for course
--

-- TABLE
CREATE TABLE COURSE_LABELS (
  COURSE_ID INT NOT NULL,
  LABEL_ID INT NOT NULL,
  -- technical attributes of the table
  CREATED_AT TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR(20) NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR(20) NOT NULL,
  VERSION INT NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE ON COURSE_LABELS TO CONNECT;

-- constraints
ALTER TABLE COURSE_LABELS ADD CONSTRAINT PK_COURSE_LABELS PRIMARY KEY (COURSE_ID, LABEL_ID );
ALTER TABLE COURSE_LABELS ADD CONSTRAINT FK_COURSE_LABELS1 FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID) MATCH FULL;
ALTER TABLE COURSE_LABELS ADD CONSTRAINT FK_COURSE_LABELS2 FOREIGN KEY (LABEL_ID) REFERENCES LABEL (ID) MATCH FULL;

